# Site settings
site_name: "DZ Playground"
title: DZ Playground | Experimenting with technology.
slogan: "Experimenting with technology"
description: "DZ community of makers"
url: "https://dz-playground.com"
author:
  name: "Yacine OUNNOUGHI "
  email: "ounnoughiyacine@gmail.com.com"
  url: ""

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site/
permalink: /:title
paginate: 8
paginate_path: /page:num/

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-target-blank
  - jekyll-seo-tag

target-blank:
   noopener: false
   noreferrer: false

sass:
    style: compressed


excerpt_separator: "<!-- excerpt end -->"

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
