# Site settings
site_name: "DZ Playground"
title: DZ Playground | Experimenting with technology.
description: "DZ community of makers"
url: ""
author:
  name: "Yacine OUNNOUGHI "
  email: "ounnoughiyacine@gmail.com.com"
  url: ""

# Build settings
baseurl: "dz-playground.com"
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/


# Markdown Settings
kramdown:
    toc_levels: 1..3

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins: [jekyll-paginate, jekyll-target-blank]

  # - jekyll-diagrams

# Custom variables
version: "0.0.1"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
